ciderapp/Cider

src/main/lastfm.js
src/renderer/index_old.html
src/renderer/views/components/fullscreen.ejs
src/renderer/views/components/mediaitem-list-item.ejs
src/renderer/views/components/queue-item.ejs
src/renderer/views/components/queue.ejs
src/renderer/views/main.ejs

TL;DR: Apple uses it so why not?
I don't know JavaScript. I have built my changes and tested things out but I am not sure if I did everything correctly. Please advice if I have done any damages.
Apple Music's iOS app, Web Player and iTunes all uses the U+2014 EM DASH: — symbol to separate artist with the album.
Cider is currently using a normal hyphen (U+002D HYPHEN-MINUS: -) to do this.
**Apple Music Web Player (beta)**
**Cider, as of commit ffc55b6b64813c58404ef762bca285b9cf567f3e**
I have replaced most, if not all, of the hyphens separating artists and albums with em dashes. I may be missing some of them, so this PR is a draft state right now.
*Note:* Code editors and monospace fonts will shorten the em dash (longer than full-width) to full-width length, so it will look exactly the …

Change hyphens into em dashes for separators

---

src/renderer/views/components/mediaitem-square.ejs
src/renderer/views/components/menu-panel.ejs

In order to keep the context menu inside the window when it would otherwise be out of bounds, the application snapped it to as far as it could go without surpassing the window's width and height. However, this positioning doesn't feel natural. Using Discord's context menu as an example, the context menu should align in the opposite direction of the mouse if it will go out of bounds.
**Before, red arrow indicating the point where user opens the context menu.**
**After, red arrow indicating the point where user opens the context menu.**
**Discord, as an example. Mouse is indicated at green arrow.**
The album display, `mediaitem-square`, has been causing me issues with accidental inputs, activating their click event despite clicking outside of their shape. I believe the hitbox/clickbox of …

Minor UX Improvements: Context Menu Position and Album Hitbox

---

src/renderer/style.less
src/renderer/views/main.ejs
src/renderer/views/pages/artist.ejs
src/renderer/views/pages/search.ejs

A feature on the iOS client of Apple Music, think it's nice to replicate on Cider.
A feature on the iOS client of Apple Music, think it's nice to replicate on Cider.
The ellipse icon was off-centered, so kind of bugged me a bit.
The current volume slider in display--small is styled as the default slider from vue.js.
From the last PR, some of the songs with no album names caused the song title to be off-centered so this should fix the centering.
When you play a video on the client, the em dash is always in nowPlayingTrack even when there's no album name.

misc improvements

---

src/web-remote/style.css

Cider's WIP web-remote isn't centered properly on a landscape view. Some CSS has been changed in order to properly size and center the elements in the main view. The screenshots below show the fix in action with a few different screen sizes. All are rendered using Firefox on Windows.

Center Web Remote Landscape

---

src/main/base/store.ts
src/main/base/win.ts
src/renderer/index.js
src/renderer/style.less
src/renderer/views/components/miniplayer.ejs
src/renderer/views/pages/settings.ejs

itunes mini player + music app on macos do this, so decided to whip up a rough PR. stuck the toggle in experimental right now, but feel free to move it or to chop and change the PR in whatever way (or reject it), lmk if there are any changes you want done.
currently working on linux for me, but assume it should be fine on other platforms looking at the [documentation](https://github.com/electron/electron/blob/main/docs/api/browser-window.md#winsetalwaysontopflag-level).
video of functionality, though it's self-explanatory tbh:
https://user-images.githubusercontent.com/23528200/150878858-3c979a12-958a-4b51-b6c4-2b8d0fa7490f.mp4

settings toggle for miniplayer to appear on top of windows.

---

src/i18n/en_GB.jsonc

This PR changes English (UK) to reflect British English, with 'izer' and 'ization' being 'iser' and 'isation' respectively.

i18n: Changed English (UK) into a main language rather than a fun language

---

src/main/base/plugins.ts

This fixes loading plugins when they're placed in `%APPDATA%\Cider\plugins`.
This probably needs more testing, I've only used Cider on a Windows machine.

Fix "TypeError: plugin is not a constructor" when trying to load plugin from user path.

---

src/i18n/hu_HU.jsonc

IMPORTANT NOTE: The term "show" in Hungarian is "megjelenítés" and the word shall be conjugated, in which case the "Cider" word shall be placed before the term ("Show Cider" -> "Cider megjelenítése"). And in the translation file only the term "Show" can be translated, so in this case I could only solve this problem by writing "A következő megjelenítése: Cider" which is a translation of "Show this: Cider" which is not the best translation but with this issue it cannot be translated any better.

Updated the term show (important note in ext desc)

---

src/i18n/de_DE.jsonc

Admittedly, "Play" does not feel right when next to all the other German words in an Album menu.
In the original iTunes App, it also says "Abspielen" instead of "Play".

Update german translation

---

package.json

Windows exe file name is different from latest.yml, casing 404 error.
`Error: Cannot download "https://416-429851205-gh.circle-artifacts.com/0/%7E/Cider/dist/artifacts/Cider-Setup-1.1.416.exe.blockmap", status 404: Not Found`
Proposed change: rename the exe file to match the latest.yml

Fix windows auto update

---

.circleci/config.yml

```
[2022-02-15 17:28:30.126] [error] Cannot download differentially, fallback to full download: Error: Cannot download "https://478-429851205-gh.circle-artifacts.com/0/%7E/Cider/dist/artifacts/Cider-Setup-1.1.428.exe.blockmap", status 404: Not Found
at ClientRequest.<anonymous> (C:\Program Files\Cider\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:288:11)
at ClientRequest.emit (node:events:394:28)
at ClientRequest.emit (node:domain:475:12)
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:6829)
at SimpleURLLoaderWrapper.emit (node:events:394:28)
at SimpleURLLoaderWrapper.emit (node:domain:475:12)```

Also copy blockmap for partial download

---

src/main/base/browserwindow.ts
src/renderer/index.js
src/renderer/views/components/mediaitem-square.ejs
src/web-remote/views/components/mediaitem-square.ejs

First I like to apologize for not using the correct target branch in the first PR. I didn't even check the auto selected one on the GitHub Desktop UI.
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

src/renderer/views/pages/artist-feed.ejs
src/renderer/views/pages/home.ejs

Addresses #324. Apple limits the number of artists you can query at a single time to 50. To deal with following more than 50, batch the following artists into groups of 50 or less, and then send multiple requests in parallel.

Bugfix: batch artist releases

---

src/main/index.ts
src/main/plugins/lastfm.ts

This PR fixes last.fm's plugin which broke in the recent refactor. This was due to the fact that the bespoke 'nowPlayingItemDidChangeLastFM' never got called due to it being passed a non existent plugin name of 'lastfm' rather than 'lastfm.js', however the 'onPlaybackStateDidChange' was called due to it being a general IPC call, resulting in behaviour of updating 'Now playing' but never scrobbling.

last.fm: fix call to nowPlayingItemDidChangeLastFM

---

src/main/base/utils.ts

```
[2022-03-01 08:24:54.075] [error] TypeError: autoUpdater.checkForUpdate is not a function
at Function.checkForUpdate (C:\Program Files\Cider\resources\app.asar\src\main\base\utils.ts:161:27)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at IpcMainImpl.<anonymous> (C:\Program Files\Cider\resources\app.asar\src\main\base\browserwindow.ts:976:13)
[2022-03-01 08:24:54.075] [error] (node:29508) UnhandledPromiseRejectionWarning: TypeError: autoUpdater.checkForUpdate is not a function
at Function.checkForUpdate (C:\Program Files\Cider\resources\app.asar\src\main\base\utils.ts:161:27)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at IpcMainImpl.<anonymous> (C:\Program Files\Cider\resources\app.asar\src\main\base\browserwindow.ts:976:13) …
```

Fix update

---

src/main/plugins/discordrpc.ts

Allow reconnecting to DiscordRPC after the socket has closed. There is otherwise no check for this and Cider keeps sending to the dead RPC instance

DiscordRichPresence: Attempt to reconnect after connection close

---

src/main/plugins/discordrpc.ts

This could possibly also be fixed in cider-preload.js but might break things that expect the old `attributes.startTime` and `attributes.endTime`

DiscordRichPresence: Fix timestamps when resuming from pause

---

README.md

The link to open the flathub page of the project is repeated, one of the repeated elements has been removed.

Removed repeated flathub link

---

src/renderer/views/app/sidebar.ejs

I think this shortcut is a good addition to Cider; looks neat and fitting as well. Works seamlessly both, with `Show Personal Info` turned on and off.
Thank you!

Shortcut to go to account settings when clicked on profile (box) in sidebar

---

src/renderer/views/pages/cider-playlist.ejs
src/renderer/views/pages/playlist-inline.ejs

With this PR, Cider will also display the album genre right above the album release date and other information.
This also resolves this issue https://github.com/ciderapp/Cider/issues/302.
Thank you!

Displays album genre, even in inline album view

---

src/renderer/views/app/sidebar.ejs

This shortcut is not only a good addition but it can also be used as an indicator to show if private session is turned on. Works flawlessly too.
Thank you!

Adds `Disable Private Session` button to menubar when Private Session is enabled.

---

src/renderer/views/pages/search.ejs

This PR adds and shows recently played tracks just like on History Page but inside the Media-Square item. The Media-Square items have been scaled down to match that of the categories present just down below.
This would be a great addition to Cider as it is a great shortcut to play previously searched and played tracks. This has been tested and works, Mergeable.
Thank you!

Shows 10 `Recently Played Tracks` in Search Page inside individual Media-Square Item.

---

cider.lock

Don't know why cider needs in pkgbuild a file.lock autogenerated, but wherever this fixed fetch packages in arch PGKBUILD compilation 
Building Cider on v1.4.3.3111.084d9157 : [Install Build Dependencies] | Build | Done
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/bitfocus/node-dns-js.git
Directory: /home/matt/.cache/yay/cider-git/src/Cider
Output:
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS: Gambare Gambare Cider Team, Love this project.

Cider PKGBUILD Test

---

src/renderer/views/pages/cider-playlist.ejs

A small update to the new album view that hides the tab controls when they are not necessary (only one tab exists).

Album view: hide tab controls when only one tab exists

---

src/i18n/en_US.json
src/i18n/source/en_US.json
src/main/base/store.ts
src/main/plugins/menubar.ts
src/renderer/main/events.js
src/renderer/views/pages/settings.ejs

This PR allows users to edit their predetermined key binds.
Works with Darwin platform as well by using Option and Command instead of Control and Shift.
As of now, it only allows users to make a keybind combination of two keys only. In case the Escape key is pressed, it stops recording the keybind.
In this PR, I also:
* Added two new variables to i18n, `settings.notyf.general.keybindings.update.success` and `settings.prompt.general.keybindings.update.success`
* Moved a few key binds from `src/renderer/main/events.js` and added it to the menu bar template
Thank you!

Added update keybind feature.

---

src/renderer/main/vueapp.js

This fixes a bug so that Cider still prefers Musixmatch lyrics instead of QQ when there isn't any translation available.
(You will get the original lyrics if lang=disabled)
The lang check is not really needed there, because it will be checked again in the method getMXMTrans.
also prevents this issue a bit: https://github.com/ciderapp/Cider/issues/923

prefer musixmatch instead of qq

---

src/renderer/main/vueapp.js

There are times where nowPlaying._context is undefined, so I added a check around it's presence for enabling the 'showInMusic' menu item.
One way to replicate the issue:
- Navigate to the songs page
- Shuffle songs
- Right click the now playing bar OR click the bar's ellipsis in attempt to open a context menu

Fix now playing context menu not rendering from 'songs' page

---

src/renderer/views/components/queue.ejs

With very large queues (shuffling all songs in a large library, for example) the queue UI can lag quite a bit. This PR limits the displayed queue to a sensible 50 items. If 50 is too small, too large, it shouldn't be much work to make this a configurable setting. The displayed queue is recomputed when the queue changes- it should always display the next 50 items or the end of the queue.

Limits the display of very large queue items to 50 at a time

---

src/renderer/style.css
src/renderer/style.less

macOS: fix back button padding

---

src/renderer/main/vueapp.js

Currently, the refreshPlaylists() method sets the playlists state to the cached playlist, but the cache is outdated in some cases (when playlists are edited, created, or deleted and refreshPlaylists() is called subsequently) and results in a strange UI lag mentioned in #864 .
To fix this we introduce a skipLocal arg that skips setting the state to the cached version and instead waits for the API call to finish and just builds the cache.
Closes #864

Attempted fix at #864

---

package.json

#575 reported that the media keys in the snap release are broken, however apparently the user used a work-around to fix it. Does not change the fact it's still broken in the current release on the Snap Store.
This PR fixes the media keys for the snap package for good by adding the mpris slot for the snap package.

Add mpris slot for snap package

---

src/renderer/views/pages/cider-playlist.ejs

This PR adds search functionality to cider-playlist (applies to albums and playlists).
To ensure it's possible to search for an album's title track, this was the logic followed:
| Search term | Album  | Playlist |
| ------------- | -------------  | ------------- |
| item-name | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| artist-name  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| album-name  | <ul><li> [ ] </li></ul> | <ul><li> [x] </li></ul> |
Here's how it looks:
Additionally, the changes made to the cider-playlist's `watch`  handler fix #1046

Add search bar to cider-playlist

---

src/renderer/less/elements.less

Another small UX/UI fix and improvement
Before:
After:

Design flaw fix for library artists page

---

src/renderer/less/elements.less

A very short commit that aims to fix the huge margin to the search hints on top and improved left and right margin.
Before:
After:

Search-hints-container top and padding margin

---

src/renderer/style.less

Adds an animation to the lyrics that makes them look more natural.
https://user-images.githubusercontent.com/79590499/171214686-10abe98e-e36f-4f84-8c7d-2d15c5741510.mov

Add Smooth Lyric Animation

---

src/i18n/en_US.json
src/renderer/main/vueapp.js
src/renderer/views/components/audio-controls.ejs

As a new user of Cider, I was very confused by what dBFS meant in the volume control so I decided to change it to something a lot more user friendly whilst still giving users the option to switch back to the previous volume control tooltip. I've added the basic functionality of being able to switch between the two styles of tooltips.
This was made with new users in mind, so anyone who installs Cider for the first time will see a percentage volume control which is probably something they're more familiar with rather than in dBFS.
With advanced volume control switched off
Where you can find the toggle switch

Added basic/advanced volume control tooltip

---

src/renderer/main/vueapp.js

Changed the code to use Electron's built in setZoomFactor to handle UI scaling. This fixes the tooltips not being positioned correctly when hoving over elements when UI is scaled. Media and Volume controls will now correctly reposition itself at the bottom when the UI is scaled and elements at the top start overflowing.
This also fixes issue #862

Update to use setZoomFactor method to handle UI scaling

---

src/renderer/less/elements.less

Adjusted the height of the media cards in "Listen Now" so that the subtitle no longer clips at the bottom
Before:
After: 
This will also fix issue #1126

Adjust height for media card so subtitle fits in card

---

src/renderer/audio/audio.js

By having this function as synchronous, it will present an error whenever someone with AudioContext disabled tries to play a track and Cider will give up on playing said track.
Checked the code before the Phase 1 update, and this function was asynchronous, therefore reverting it back to async. Tracks now play even with AudioContext disabled.
This might potentially fix issue #1128

Fix playback issues where user has AudioContext disabled

---

src/web-remote/index.js
src/web-remote/views/index.ejs

Currently the active lyric element is constantly being scrolled into view even when the user is trying to do it themself, I changed this behavior, temporarily disabling scrolling active lyric into view while the user is scrolling

Disable lyrics scrolling while the user is doing it themself

---

src/renderer/views/pages/plugins-github.ejs
src/renderer/views/pages/themes-github.ejs

Currently some themes are missing from the GitHub themes page due to the GitHub API's default per_page parameter being 30, and there currently being 38 themes out in the world. This change increases that limit to 100 which should be good for a long while. In the future, if there are ever more than 100 themes (lmao), may have to make use of the API's pages feature to be able to list them all.

GitHub Themes/Plugins list limit 30 -> 100

---

src/renderer/style.less

I have re-added Noto CJK fonts (Noto Sans JP/KR/SC/TC) to the `font-family` for the entire Cider UI (it was removed as part of the change to Pretendard as Cider's English UI font), as it was displaying Japanese characters with varying font weights.
**Comparison:**

Re-add Noto CJK to the font stack

---

src/renderer/less/pages.less

fixed podcast title padding in podcast details
before:
after:

fixed podcast title padding in podcast details

---

src/renderer/main/vueapp.js
src/renderer/views/app/chrome-top.ejs

Following the latest changes to the collapsible sidebar, this PR removes the automatic opening of the sidebar when the quick nav button is clicked.

Remove automatic opening of the sidebar on quick nav click

---

.gitignore
src/renderer/less/pages.less
src/renderer/views/pages/artist.ejs
src/renderer/views/pages/cider-playlist.ejs

this basically works but code is spaghetti.
please send help.
**Todo:**
here is an image since you guys like them so much:

album banners (aka editorial artwork) (aka album hero)

---

src/renderer/views/components/mediaitem-list-item.ejs

This condition is preventing the heart icon from showing up if the song is playing.
Before:
After:

Remove conditional rendering of the heart icon

---

src/renderer/main/vueapp.js

This PR attempts to resolve #1217. It makes album lookups much faster by storing them in an object versus having to search in a list.
This cut down my time to sort a library from over a minute to a few seconds.

Speedup sorting of songs by date added

---

src/i18n/en_OWO.json
src/i18n/en_PISS.json
src/i18n/en_US.json
src/i18n/hi_IN.json
src/i18n/source/en_US.json

This PR modifies the localization files to change the text that shows in the full screen player when lyrics for a track are not found. The small change improves conciseness, in addition, I personally find that the existing text feels weird and somewhat out of place. This is 100% a nitpick change.
Affected localization:
en_US, en_US, hi_IN (?)
as well as en_PISS and en_OWO (Translated using https://aqua-lzma.github.io/OwOify/)

Change No Lyrics Message in Full Screen Player

---

README.md

This pull request fixes the download links within README.
**Before:** README links points to ciderapp/Cider's release page  
**After:** README links points to ciderapp/cider-releases's release page

README download links fix

---

src/renderer/style.less

Made changes to the background of the `Fullscreen View` button. It now has a gray-to-transparent gradient. Looks more fitting
Preview:
* Old
* New

Add gradient to lyric-footer

---

src/main/base/wsapi.ts
src/renderer/main/wsapi_interop.js
src/web-remote/index.js
src/web-remote/style.css
src/web-remote/views/index.ejs

Hope I'm not being a pain. I like the web remote, but one thing that I've wanted to do is like/dislike a song, and add it to my library. This PR seeks to add these features bu expanding on the existing song actions menu, and implementing the necessary socket communication. 
Clicking on one of Love/Dislike will then make that option lighter and disabled. Clicking on Add to library will toggle remove from library (although it may take a while for Cider to actually recognize it's removed because apple .-.)
I also commented out a few of the console.log, because they pollute the console.

Add ratings, library change to web remote

---

src/renderer/views/components/fullscreen.ejs
src/renderer/views/components/sidebar.ejs

idk why this change didn't exist yet

Disable Fullscreen view when artist/album name is clicked.

---

README.md

Hi @Cider_devs,
I have created this Pull Request because I have resolved this [request for a Chocolatey package](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1298) and now, we can install **cider** using Chocolatey ([the package is available here](https://community.chocolatey.org/packages/cider)).
For now, only the version `1.5.1` is available on Chocolatey, and the version `1.5.4` is for now waiting for the Chocolatey moderators to be reviewed.

Adds the Chocolatey package as a way to install Cider

---

package.json

Cider is indeed an electron app which comes with the cost of fat, massive binaries.  With the recent releases of Apple Silicon machines, Apple decided that universal binaries would be a good idea to solve the problem of confusing customers about the two CPU architectures.  However, one of the caveats of universal binaries is bigger binary sizes because universal builds usually contain both Intel and Apple Silicon code despite a Mac would not need both the Intel and AS code which only has to run one of the two codebases.  I would suggest Cider start releasing separated macOS builds for both Intel and AS architectures to slim down the size of the Cider app.  The scripts use the `ditto` which does not require rebuilding for each architecture but rather separates the universal build into two …

Added scripts to produce separated macOS builds for different architectures

---

src/renderer/less/pages.css
src/renderer/less/pages.less
src/renderer/views/pages/library-albums.ejs

This PR:
* Makes the search and filter options, and pagination buttons in one line. Looks more fitting and alike library-songs.
* Makes them sticky, thus no need to scroll back up to use the search bar, et cetera.
Preview:

Change Album Search and Pagination Layout

---

src/main/base/app.ts

This really simple change allows users to not only open `cider://` URLs in the app, but also native iTunes `itms://` and `itmss://` as well as native Apple Music `music://` and `musics://` links.
While the app is registered by default to handle these URLs (at least on Windows), Cider refused to accept any links if they were not specifically `cider://` links. Since the `cider://` URL format is pretty much the same as any of the native URL's formats, Cider already has a parser for these URLs. This single-line change only tells it to apply its parsing and opening logic to the native URL prefixes as well.

Support for opening iTunes and Apple Music links

---

src/i18n/en_US.json
src/main/plugins/discordrpc.ts

this fixes https://github.com/ciderapp/Cider/pull/1435 because discord rpc does not support 3 buttons.
it now shows "view on other platforms" with the song.link link instead of "view on apple music"

fix discord rpc

---

src/renderer/less/elements.less
src/renderer/views/components/smarthints.ejs

This PR adds a play button on top of artworks on `mediaitem-smarthints`, Just like how on iTunes application.
Preview:
https://user-images.githubusercontent.com/79590499/191010286-52c861fd-0752-4b6b-bf03-e638f9754d0a.mp4

Play button for mediaitem-smarthints

---

src/renderer/main/vueapp.js

Currently when sorting by date added, the order within albums is incorrect, because the timestamp is the same for tracks that are added as part of an album. Falling back to sorting by track number solves this.

Fix album track order for date added sorting

---

src/main/base/store.ts
src/renderer/less/directives.less
src/renderer/main/vueapp.js
src/renderer/views/app/chrome-bottom.ejs
src/renderer/views/components/sidebar.ejs

Clicking on artwork on `chrome-bottom` section takes the artwork to the sidebar (Works only on Mojave)
Preview:
https://user-images.githubusercontent.com/79590499/200188862-e4df5a03-90d8-4008-8b34-8bbe638d6b16.mp4

Add expand artwork feature

---

src/renderer/views/components/sidebar.ejs

Use sticky position on expanded artwork instead of absolute, this allows users to scroll and view content that would be hidden behind the expanded artwork. It also aligns the artwork perfectly in centre.

Use sticky position instead of absolute

---

src/main/base/browserwindow.ts
src/renderer/views/components/settings-window.ejs

Allows Linux users to set transparency by adding the toggle to advanced settings and by adding the appropriate Electron app configuration values.
Example:

Add transparency option to linux

---

src/main/base/app.ts

Fixes #1624 and #1514.
I believe the bug works the following way: [`indexOf` returns `-1`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf#return_value) if the substring is not found, that becomes `true` after cast to boolean. This results in overriding `--enable-features=UseOzonePlatform` and `--ozone-platform` flags when running on linux. Please note that I have zero experience with js, but the bug is pretty obvious and this fix allows me to run the app natively on sway.

fix SteamOS check

---

src/main/base/app.ts

Fix the command injection in link handler. The second one can be triggered from browser using `location.href = "cider://'+alert(123)+'"` currently.

Fix command injection in link handler
