- src/renderer/index.js
- src/renderer/views/main.ejs
- src/renderer/views/pages/library-albums.ejs
- src/renderer/views/pages/library-recentlyadded.ejs
> add recentlyadded view & update sorting function

- src/renderer/index.js
This fixes sorting by genre and will no longer convert date to timestamp which was unnecessary.
> fix album & song sorting function

- src/renderer/index.js
There is a bug that blocks the media change and the notification. It happens because the function accepts an object with undefined parameters.
The fix is just a check of whether the parameters are undefined.
> fix trying to notify using undefined data

- src/preload/cider-preload.js
https://github.com/ciderapp/Cider/pull/89#issuecomment-1008152422
> Replace conditional operators with nullish coalescing operators

- src/main/cider-base.js
> Fix Acrylic v2

- package.json
- src/main/cider-base.js
acrylic problematic and unnecessarily uses up resources only for it to be covered by artwork-bg
> get rid of acrylic

- src/renderer/views/components/mediaitem-list-item.ejs
This may have unexpected side effects that idk about but I haven't found any yet
> Fixed #114

- src/renderer/views/main.ejs
Hides both drawer and Lyric button while lyrics are not fully loaded.
Preview:
https://user-images.githubusercontent.com/71800112/149300059-06aff898-7d40-4703-988a-82b138370568.mp4
> Show lyrics button only if there are lyrics

- src/renderer/style.less
- src/renderer/views/components/queue.ejs
> change of the ugly "AUTO" button to the ∞

- src/renderer/style.less
- src/renderer/views/main.ejs
Indicate if a song is explicit in the now playing songs.
> Add explicit icon next to song name

- src/renderer/views/components/libraryartist-item.ejs
Added context menu support for the artist list-items in the `library-artists` page.
**As a note:** the "Go to Artist" button takes the user to the artist's page on Apple Music. As normal, clicking on the list-item still takes the user to the `collection-list` page.
> Context Menu - Library Artist Item

- src/renderer/style.less
Least tedious PR ever because there are no divs to read and no conflicts!
I used a stupid ruler on my monitor to check the alignment and before this commit, the numbers would be like 5 px off.
> Song duration alignment

- src/renderer/index.js
- src/renderer/views/components/fullscreen.ejs
- src/renderer/views/main.ejs
added a volume condition for the mute/unmute feature, also removed last PR commit of hiding album name when hovered over nowPlayingItem
> volume change fix

- src/renderer/style.less
- src/renderer/views/components/mediaitem-list-item.ejs
- src/renderer/views/pages/podcasts.ejs
https://user-images.githubusercontent.com/45437968/150668512-bbe12d7e-a2fc-44a4-a87a-beea45fef5ca.mp4
> ui changes

- src/renderer/index.js
> Fix playlist queue problem

- src/i18n/en_US.jsonc
> Revert "Massive i18n push"

- src/i18n/en_US.jsonc
- src/i18n/ja_JP.jsonc
- src/i18n/zh_CN.jsonc
- src/i18n/zh_TW.jsonc
Good to merge
Only merge until I update this message.
> i18n update

- src/i18n/ja_JP.jsonc
thanks to noyciy7037#5836 for the corrections
> [i18n] ja_JP minor corrections

- src/i18n/zh_CN.jsonc
Some translation are clunky in my opinion. Also translated an untranslated string.
> Update Chinese translation

- src/i18n/ja_JP.jsonc
Decide on a formal notation: 
- カバーアート/アートワーク/ジャケット写真...
- ()、（）
> ja_JP minor update

- src/i18n/el_GR.jsonc
> Update Greek Translation

- src/i18n/zh_HK.jsonc
> Update on zh_HK translation

- src/main/plugins/discordrpc.ts
needs @cryptofyre to add some stuff in cider-preload
> [WIP] DiscordRPC - Add Open in Apple Music Button

- src/main/base/store.ts
- src/renderer/audio/audio.js
- src/renderer/views/components/equalizer.ejs
> Equalizer Presets

- src/i18n/ja_JP.jsonc
- src/i18n/zh_CN.jsonc
- src/i18n/zh_TW.jsonc
> its like three i18n strings just merge

- src/preload/cider-preload.js
this causes mobile (specifically iOS) Apple Music to not display the song. 
P.S.
;) I know who forgot
> Someone forgot about storefront lol

- src/i18n/zh_yue.JSONC
Updated some strings that I think it'd suit more, feel free to revert / modify
> Update Cantonese Translation

- src/i18n/zh_yue.JSONC
> Fix missing comma

- src/i18n/de_DE.jsonc
This adds a German translation.
I am a native German speaker myself, and all of the translations were made by hand and proofread twice.
> Add german translation

- src/renderer/views/components/add-to-playlist.ejs
> I fucked up last time i tried to do localization and didnt realize that I made a error

- src/i18n/it_IT.jsonc
> Italian translation

- src/i18n/README.md
- src/i18n/en_PISS.jsonc
- src/i18n/en_US.jsonc
- src/renderer/views/pages/cider-playlist.ejs
> Resolved issue #281

- src/i18n/README.md
- src/i18n/en_SGA.jsonc
- src/i18n/en_US.jsonc
- src/i18n/zh_HK.jsonc
- src/i18n/zh_yue.jsonc
- src/renderer/index.js
- src/renderer/style.less
- src/renderer/views/components/equalizer.ejs
> Irregular update 02/02

- src/i18n/README.md
- src/i18n/en_SGA.jsonc
- src/i18n/en_US.jsonc
- src/i18n/zh_HK.jsonc
- src/i18n/zh_yue.jsonc
- src/renderer/views/app/sidebar.ejs
- src/renderer/views/pages/settings.ejs
> Irregular update 04/02

- src/i18n/sv_SE.jsonc
Updated sv_SE.jsonc by correcting spelling and correcting my word choice after using the language for a few days in Cider so it makes sense in the context. 
This will probably be the last edit until more terms and such are added as the language should be good for now.
> Updated sv_SE.jsonc

- src/i18n/en_PISS.jsonc
> en_PISS: Update 2021-02-04 07:26

- src/i18n/ko_KR.jsonc
Hello, I appreciate for this nice project. I translated i18n file to Korean.
Can anyone check this PR? Thanks. :)
**[Preview]**(Note: It's Korean.)
> Initial Korean Translation Support

- src/i18n/README.md
- src/i18n/en_SGA.jsonc
- src/i18n/en_US.jsonc
- src/i18n/zh_HK.jsonc
> Irregular update 05/02

- .gitignore
- src/i18n/de_DE.jsonc
- src/main/base/app.ts
*and add yarn.lock to .gitignore*
> Update German translation

- src/renderer/views/pages/settings.ejs
I done mistake. I fix mistake.
> Fix typo in settings.ejs

- .circleci/config.yml
- package.json
- resources/appendCommitToVersion.js
Local builds will not compile after c1fb6ed because of the version not matching the format `x.x.x`. This PR fixes that.
> Fix local builds

- src/i18n/tr_TR.jsonc
> Updated TR Language

- src/i18n/hi_IN.jsonc
Hindi Language Option for Cider, update on first 20-30 lines from English to Hindi. More to come soon!!
> Starting Hindi translation

- src/i18n/hi_IN.jsonc
- src/i18n/in_ID.jsonc
- src/i18n/sk_SK.jsonc
- src/renderer/views/components/miniplayer.ejs
Reopen due to wrong branch
Tasks:
> Irregular update 09/02

- src/main/plugins/webNowPlaying.ts
Plugin to work with the Rainmeter extension. No configuration needed.
Untested on other operation systems other than Windows. Ideally it should be disabled for OSs that don't have Rainmeter but I'm not sure how to do that.
> Create WebNowPlaying plugin

- src/i18n/hi_IN.jsonc
- src/i18n/hu_HU.jsonc
I changed some strings in the Hungarian (hu_HU) language file. I also made a temporary fix for the Hindi i18n info, because in the app, it showed as English.
> Translation update

- src/renderer/index.js
V1 adds
* Websockets
* iCloud artwork api
* better json responses
> Switch to v1

- src/i18n/ro_RO.jsonc
I re-did the whole Romanian translation as it was mostly not translated.
> Full Romanian Translation

- src/main/plugins/webNowPlaying.ts
Finalized everything. I consider this finished unless there are bugs found.
> Update WebNowPlaying plugin.

- src/i18n/de_DE.jsonc
Apple Music App is using "Wiedergabe" instead of "Abspielen"
> updated german language

- src/i18n/README.md
- src/i18n/en_PISS.jsonc
Note: I will be off Discord for the next few months and will **not** be able to maintain this language. If someone could help out it'd be greatly appreciated.
Peace!
> en_PISS 2022-02-11

- src/i18n/README.md
- src/i18n/en_QUK.jsonc
- src/i18n/en_SGA.jsonc
- src/i18n/en_US.jsonc
- src/i18n/sk_SK.jsonc
- src/i18n/zh_HK.jsonc
> Irregular update 12/02

- src/i18n/source/en_US.json
- src/renderer/views/components/plugin-menu.ejs
- src/renderer/views/svg/x.svg
Added a message in plug-in menu.
reopen due to new i18n format
> Irregular update 21/02

- src/renderer/views/components/mediaitem-list-item.ejs
> Make song title have text-overflow-ellipsis

- .circleci/config.yml
- package.json
- winget.json
making a silent installer for use in updating Cider in Winget repo
> Add Winget building to CircleCI artifacts

- src/renderer/views/app/chrome-bottom.ejs
- src/renderer/views/app/chrome-top.ejs
it basically looked the same but you couldn't click on it
> Make lyrics button more transparent when not available

- src/renderer/less/bootstrap.less
( no clue why it did that at the end of file as i never touched that but ¯\_(ツ)_/¯ )
> fix being able to highlight tooltip text

- src/renderer/main/vueapp.js
> Search fix

- src/i18n/en_US.json
- src/i18n/source/en_US.json
- src/main/plugins/menubar.ts
- src/renderer/views/components/castmenu.ejs
- src/renderer/views/components/equalizer.ejs
- src/renderer/views/components/spatial-properties.ejs
- src/renderer/views/pages/about.ejs
- src/renderer/views/pages/library-recentlyadded.ejs
- src/renderer/views/pages/settings.ejs
> Irregular update 22/03

- .circleci/config.yml
- README.md
- src/renderer/audio/audio.js
- src/renderer/views/components/mediaitem-list-item.ejs
it was written before in javascript, I just turned it into a div
> Tweak play icon to make it editable in themes

- src/i18n/en_US.json
- src/i18n/source/en_US.json
- src/main/plugins/discordrpc.ts
- src/renderer/views/pages/settings.ejs
With this PR, people can choose whether to hide buttons on their rich presence (Listen on Cider & View on Apple Music).
> Added more customizability to the Discord Rich Presence Plugin on Cider (Buttons)

- flatpak/cider-wrapper
- flatpak/flathub.json
- flatpak/sh.cider.Cider.metainfo.xml
- flatpak/sh.cider.Cider.yml
I'm the Flatpak Maintainer and these are all the changes I've made to the one you guys have here to bring it up to date with what I have going on the [Flathub repo](https://github.com/flathub/sh.cider.Cider).
> Update Flatpak manifests

- src/renderer/less/pages.less
> Adds gradient animation to the `Replay <year>` button on home screen

- src/renderer/views/pages/cider-playlist.ejs
- src/renderer/views/pages/playlist-inline.ejs
added the album genre under the album name and also added the release year for albums to it
(it also fills more space)
> move album genre under album name and add release year

- src/i18n/en_US.json
- src/i18n/hu_HU.json
- src/i18n/source/en_US.json
I added like 10 new strings to Hungarian (hu_HU) language files, and fixed a typo in the English (US) files.
> Added lots of new strings and fixed a typo

- src/renderer/less/pages.less
Added gradient animation like the one on the replay button on replay viewport.
> Added gradient animation on Replay Viewport

- src/main/base/store.ts
https://discord.com/channels/843954443845238864/843954444747669507/962011810070954065
> Changed Volume Step default from 10% to 5% (approved by Maikiwi)

- src/renderer/less/elements.css
- src/renderer/less/elements.less
- src/renderer/style.css
I removed the hover effect from the artist-card and aligned the artists image like the genre/album-title for a better UI look
> removed hover for artist-card and re-align

- src/i18n/zh_CN.json
- src/renderer/views/app/sidebar.ejs
> unbonk i18n

- src/i18n/README.md
- src/i18n/en_US.json
- src/i18n/source/en_US.json
Added `settings.header.connect` to en_US, source and i18n README
> Added Connect string

- src/renderer/main/vueapp.js
Also removes a useless/redundant sorting option
> Add release date sorting option to albums

- src/i18n/README.md
I also changed JSONC to JSON in the README.
> Make i18n README more up-to-date

- src/main/plugins/menubar.ts
I also added the keyboard shortcut: `CommandOrControl+Shift+I`
> Add Private Session Toggle to menubar (macOS)

- src/renderer/views/pages/replay.ejs
show played hours instead of minutes on replay page
> show played hours on replay page

- src/main/base/browserwindow.ts
- src/renderer/main/vueapp.js
Window and miniplayer remember location when they are toggled. 
Closes #519
> Move to original location on miniplayer close, and vice versa.

- src/i18n/en_US.json
- src/i18n/hu_HU.json
- src/i18n/source/en_US.json
- src/main/base/store.ts
- src/main/plugins/discordrpc.ts
- src/renderer/views/pages/settings.ejs
> Revert "Add option to hide timestamp in RPC"

- src/renderer/views/components/castmenu.ejs
> Make cast device list scrollable

- src/renderer/views/components/miniplayer.ejs
> Make Pin button on MiniPlayer interactive.

- src/main/base/app.ts
> Fix Tray icon

- package.json
- winget.json
works for Windows 11, and Linux (ubuntu) i asked from a review from Core to test AUR
> Electron 18.2.4

- package.json
- winget.json
Works for Windows and Linux, please check for AUR, mac and/or Flatpak
> Electron 18.3.0

- src/renderer/less/elements.less
Minor bug fix for the Songs Library UI issue. Here is a preview:
Before:
After:
> Songs Library UI Fix

- src/renderer/style.less
Updated the font family for lyric translations so they now match the rest of the UI
> Forgot to update the lyric translations font to match rest of UI

- src/renderer/main/events.js
- src/renderer/main/vueapp.js
- src/renderer/views/components/equalizer.ejs
- src/renderer/views/pages/installed-themes.ejs
- src/renderer/views/pages/keybinds.ejs
- src/renderer/views/pages/plugins-github.ejs
- src/renderer/views/pages/settings.ejs
- src/renderer/views/pages/themes-github.ejs
This PR:
- Translates bootbox dialog buttons
- Isolates bootbox dependency
- Uses bootbox for playlist deletion confirmation (instead of `window.confirm`)
> Bootbox dialog improvements

- src/renderer/views/pages/cider-playlist.ejs
> Add hero color to `Play` & `Shuffle` buttons

- src/renderer/less/pages.less
- src/renderer/main/vueapp.js
- src/renderer/views/components/app-content.ejs
- src/renderer/views/components/settings-window.ejs
- src/renderer/views/pages/keybinds.ejs
Well New Style
I tested only in linux, suposse this work on the others Os's (the function not changed only location xd)
> keybinds New Settings Window Format

- src/renderer/less/elements.less
- src/renderer/less/pages.less
- src/renderer/style.css
- src/renderer/views/pages/cider-playlist.ejs
This PR:
* Adds hero color to search button background
* Add hero color to more button background
* Change search button SVG color to gray to match more button SVG
Preview:
> Add color to search button background

- src/renderer/less/pages.less
- src/renderer/style.css
- src/renderer/style.less
- src/renderer/views/pages/about.ejs
> Add twitter social button for some developers in about page

- src/renderer/main/vueapp.js
- src/renderer/views/components/settings-window.ejs
Deleted 2 times plugins tab in windows-settings and leave only the independent entrie menu.
> I forgot that

- src/renderer/less/pages.less
- src/renderer/style.css
- src/renderer/style.less
- src/renderer/views/pages/about.ejs
This PR:
* Fixes the buttons on cider team list
* Fixes twitter button alignment
* Adds other devs twitter (best platform frfr)
Preview:
> Fix cider team buttons in about page

- src/renderer/main/vueapp.js
- src/renderer/views/pages/cider-playlist.ejs
before: gets genre from 1st track
now: gets genre from album data
> Fix album genre names

- src/renderer/less/ameframework.less
- src/renderer/less/bootstrap.less
- src/renderer/less/pages.less
- src/renderer/style.css
- src/renderer/style.less
- src/web-remote/ciderframework.css
Preview:
* Old
https://user-images.githubusercontent.com/79590499/177953799-3370c6a7-2e58-4b4a-8b9a-a10b3756dbd5.mp4
* New
https://user-images.githubusercontent.com/79590499/177953582-0b5b782e-e114-4afe-ad4c-b112a9a62fb9.mp4
> Fix cider team list

- src/renderer/index.js
I tested and the fallback key you are using is dead. 401s. Unusable.
> Remove dead fallback token, add error log if capi call fails

- src/i18n/es_ES.json
> i hate my life

- src/main/plugins/playbackNotifications.ts
This PR should make the notifications silent. Sorry core
I hate XML
> This should do it

- src/main/plugins/discordrpc.ts
> no more discord rpc when private session is enabled

- resources/version.sh
> [Bug] Fix version.sh ambiguous redirect warnings

- src/main/plugins/mpris.ts
- src/renderer/main/vueapp.js
I noticed that everything else was here, and wanted to add the ability to control volume as well.
> Add ability to control/view volume on MPRIS

- package.json
- pnpm-lock.yaml
- src/renderer/views/app/chrome-top.ejs
> Fix `search-hints-container` going out of screen

- src/renderer/style.less
- src/renderer/views/app/chrome-top.ejs
Hello 👋🏽 
Is there a specific reason for comment this line out? Because it looks a bit strange like that.
> BUGFIX: set background color in search hints container

- README.md
- src/renderer/views/components/c2-upgrade.ejs
mfw yall put up the wrong info into the app for 2 weeks straight
> [PR] Fix upgrade modal info, add EOL notice to README
